version: '2'

services:
  antioch:
    build: .
    container_name: antioch
    volumes:
      - .:/app

  antioch-downloader:
    extends:
      service: antioch
    environment:
      READ_FROM_DIRECTORY: /app/data
      DROP_FOLDER_LOCATION: /app/data_drop
    command: python -m antioch.downloader

  antioch-uploader:
    extends:
      service: antioch
    command: python -m antioch.uploader

  antioch-tests:
    extends:
      service: antioch
    command: tox