import os

REQ_TIMEOUT = (3, 10)
REMOVE_JSON_ON_SUCCESS = True
DEFAULT_CHUNKSIZE = 16384 # 16 * 1kB
DEFAULT_THREAD_COUNT = 2

READ_FROM_DIRECTORY = os.getenv('READ_FROM_DIRECTORY', '.')
DROP_FOLDER_LOCATION = os.getenv('DROP_FOLDER_LOCATION', 'tmp')

ERROR_FOLDER_LOCATION = os.path.join(DROP_FOLDER_LOCATION, 'errors')

DEFAULT_FOLDERS = (
    DROP_FOLDER_LOCATION,
    ERROR_FOLDER_LOCATION
)
