import os
import logging

REQ_TIMEOUT = (3, 10)
REMOVE_JSON_ON_SUCCESS = True
REMOVE_AFTER_ARCHIVED = True

ARCHIVE_THRESHOLD_BYTES = 1 * 1024 * 1024 * 1024  # 1 GB
ARCHIVE_FILENAME = 'pytube-video-archive-%s-%s.zip'

DEFAULT_LOG_LEVEL = logging.DEBUG
DEFAULT_LOG_LOCATION = os.path.join('/tmp', 'org.pytube.antioch.log')
DEFAULT_CHUNKSIZE = 16384  # 16kB
DEFAULT_THREAD_COUNT = 2

READ_FROM_DIRECTORY = os.getenv('READ_FROM_DIRECTORY', '.')
DROP_FOLDER_LOCATION = os.getenv('DROP_FOLDER_LOCATION', '/tmp/pytube/videos')

ERROR_FOLDER_LOCATION = os.path.join(DROP_FOLDER_LOCATION, 'errors')
PICKUP_FOLDER_LOCATION = os.path.join(DROP_FOLDER_LOCATION, 'pickup')

DEFAULT_FOLDERS = (
    DROP_FOLDER_LOCATION,
    ERROR_FOLDER_LOCATION,
    PICKUP_FOLDER_LOCATION
)
